### ISSUE TITLE
Train and Test sets

### ISSUE THREAD

**Issue by jsmithdlc** [Wangchangjen/ThemalPost-Data#1]
Hello,
Firstly, I want to congratulate you all for your work! Secondly, I intend to train a detector over the dataset you provide but can't find information about which images you used for training and which you used for testing. I need to know this so i can compare my own results with the ones you specify on the paper. Can you tell me?

**Comment by jsmithdlc** [comment]
Issue closed, folders Data_set1->Data_set9 belong to train set and folder Data_set_person_label to test set

**Comment by xingchenzhang** [comment]
Hi,

Could you please let me know where is the "Data_set_person_label"?

Thanks a lot!

**Comment by jsmithdlc** [comment]
Hi,
from what I recall that folder was in the same drive as the other ones. It seems as the authors might have modified access to it.

**Comment by xingchenzhang** [comment]
Thank you for the reply! 

Yes, I think so because I can't find the folder from the provided link now.

**Comment by Wangchangjen** [comment]
Sorry, I re-open the download permission for the Data_set_person_label file.

**Comment by xingchenzhang** [comment]
> Sorry, I re-open the download permission for the Data_set_person_label file.

Thank you very much! I have downloaded the file.
